### ISSUE TITLE
Downloaded AnchorDETR R50 C5 weights evaluation only got 38.5

### ISSUE THREAD

**Issue by jinfagang** [megvii-research/AnchorDETR#24]
![image](https://user-images.githubusercontent.com/21303438/143170795-09fad2bb-46a4-4bfc-8c31-c525ca383982.png)

the command am using:

```
python -m torch.distributed.launch --nproc_per_node=8 --use_env main.py --dilation False --eval --coco_path data/coco --resume workdir/r50-c5/AnchorDETR_r50_c5.pth

```

I using exactly same code in master branch, any idea?

**Comment by tangjiuqi097** [comment]
@jinfagang Hi, it is because the default type of `dilation` is `str`. So the model with `--dilation False` is still the DC5 model which does not match the weights. You can set the default value of `dilation` to `False` at the [file](https://github.com/megvii-research/AnchorDETR/blob/e9f5235d656c1582b241a07cb145c097ee0c458f/main.py#L53).

**Comment by jinfagang** [comment]
@tangjiuqi097 Oh..... this bug is really.....

**Comment by tangjiuqi097** [comment]
Now the bug is fixed.
