### ISSUE TITLE
Points visualization

### ISSUE THREAD

**Issue by Mark-Laohu** [megvii-research/AnchorDETR#32]
你好，请问learned anchor points更新后的可视化图Figure 2（b）是怎么可视化出来的，不是被embedding了吗

**Comment by tangjiuqi097** [comment]
Hi, we visualize the final [`self.position`](https://github.com/megvii-research/AnchorDETR/blob/c39246b8e8001179a18996dff0bcf1d78598deb8/models/transformer.py#L62) as the learned anchor points, which have `self.num_position` points and each of them has two dimensions (x, y). You can also create them by the `nn.Parameter(torch.FloatTensor(self.num_position, 2))` instead of the `nn.Embedding(self.num_position, 2)`, which may be easier to understand.

**Comment by Mark-Laohu** [comment]
谢谢回答，learned points生成我大概明白了，就是我想问的是learned points在训练后能可视化出来吗，paper中给的是初始化得到的图还是训练后得到的可视化图啊?

**Comment by tangjiuqi097** [comment]
The figure in paper is the final learned anchor points after training. You can visualize the `model.transformer.position.weight` in the checkpoint we provide.

**Comment by Mark-Laohu** [comment]
好的，非常感谢！
