### ISSUE TITLE
Question about the time cost per epoch

### ISSUE THREAD

**Issue by tymanman** [megvii-research/AnchorDETR#4]
I found that the time cost per epoch of this version of detr is much longer than the naive one, so, the whole time cost of 50 epochs is a little better than 500epochs of the naive one?

**Comment by tangjiuqi097** [comment]
@tymanman  Hi, 

AnchorDETR-R50-DC5 takes about 3 to 4 days to train 50 epochs for a single node with 8 2080ti GPUs.

DETR-R50-R50-DC5 cannot be trained on 2080ti even with 1 image per card, so I am not sure how long it takes. 
But I guess it will take about 1 month to be trained for 500 epochs on 8 GPUs that have the same speed as 2080ti.

You can also refer to issue [#283](https://github.com/facebookresearch/detr/issues/283) in DETR, DETR-R50-DC5-500e takes about 4 days with 64 V100 GPUs.
I believe AnchorDETR can also cost less time if you use more cards.


By the way, we modify the log output frequency from 10 to 100 iterations, I am not sure if this confuses you.

**Comment by tymanman** [comment]
thank u ,get it.Besides, I have an another question about the comparison of the performance.I wanna know whether the result table is based on the same query number of 300 for detr and Anchor DETR?

**Comment by tangjiuqi097** [comment]
@tymanman No, the performance of DETR is based on 100 queries. When increasing the number of DETR, the performance seems to degrade (refer to [#166](https://github.com/facebookresearch/detr/issues/166) of DETR). 

The object query of AnchorDETR is based on anchor point so that it has a different physical meaning, and we find 300 anchor points with 3 patterns should be more suitable. You can also refer to the Tabel 4 of the [paper](https://arxiv.org/abs/2109.07107v1) for the performance with the different number of anchor points and patterns.

**Comment by tangjiuqi097** [comment]
I'm closing this issue as I think I have answered your question, but let us know if you have further questions.
